apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flaskapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
